# -*- coding: utf-8 -*-
"""SimpleLinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FR7lzfnm2ZoG1lu6IolyRs5bc8SwJCdn

# **Simple Linear Regression**

here teh data set has linear relationships so the linear regression model works fine

best fit line on present values to predict future values

Ordinary Least Squares (OLS) is a regression technique that uses a straight line to estimate the relationship between two or more variables. The goal of OLS is to find the "best-fitting line" that minimizes the sum of squared errors between the predicted and actual values of the outcome variable.

**Importing the libraries**
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""**Importing dataset**"""

dataset = pd.read_csv('Salary_Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

"""**splitting the dataset into training set and test set**"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

"""**training the simple linear regression model on the training set**"""

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

"""**predicting test set results**"""

y_pred=regressor.predict(X_test)

"""**visualizing teh training set results**"""

plt.scatter(X_train,y_train,color='red')
plt.plot(X_train,regressor.predict(X_train),color='blue')
plt.title('Salary vs Experience (Training set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

"""**visualizing the test set results**

the regresion line we get is actually resulting from a unique equation.therefore predicted salaries of the test set will be on the same line as the predicted salaries of teh training set
"""

plt.scatter(X_test,y_test,color='red')
plt.plot(X_train,regressor.predict(X_train),color='blue')
plt.title('Salary vs Experience (Test set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

"""Using Simple Linear Regression (SLR) to predict the winner of a football game is generally not appropriate due to the complexity and nature of the problem. Here's why:

Nature of Football Game Predictions
Binary Outcome: The outcome of a football game is binary (win/loss), or sometimes ternary if you consider draws. Simple Linear Regression is designed for continuous outcomes, not categorical ones.

Complex Interactions: Football games are influenced by a multitude of factors such as team strength, player form, injuries, home-field advantage, weather conditions, and more. These factors interact in complex ways that a simple linear model cannot capture.

Why SLR is Inappropriate
Assumption of Linearity: SLR assumes a linear relationship between the predictor(s) and the outcome variable. In football, the relationship between predictor variables (like team statistics) and the game outcome is rarely linear.

Continuous vs. Categorical Outcome: SLR is used to predict a continuous dependent variable. Since the outcome of a football game is categorical, techniques like logistic regression, which handle binary outcomes, are more appropriate.

Appropriate Alternatives
Logistic Regression: This is a regression model used when the dependent variable is binary. It predicts the probability of a binary outcome (win/loss).

Machine Learning Models: Techniques like decision trees, random forests, support vector machines, and neural networks can capture complex relationships and interactions between predictors.

Ensemble Methods: Combining multiple models to improve prediction accuracy.

Example of Logistic Regression
If you want to predict the outcome of a football game, logistic regression can be a good start. Here's a simple example setup:

Data Collection: Gather data on various predictors such as team statistics, player performance metrics, historical performance, and other relevant factors.

Feature Selection: Choose relevant features like average goals per game, possession percentage, shots on target, etc.

Model Training: Train a logistic regression model on historical game data.

Prediction: Use the model to predict the probability of a team winning a game.

Logistic Regression Formula
The logistic regression model can be represented as:
logit
(
𝑝
)
=
log
⁡
(
𝑝
1
−
𝑝
)
=
𝛽
0
+
𝛽
1
𝑋
1
+
𝛽
2
𝑋
2
+
…
+
𝛽
𝑛
𝑋
𝑛
logit(p)=log(
1−p
p
​
 )=β
0
​
 +β
1
​
 X
1
​
 +β
2
​
 X
2
​
 +…+β
n
​
 X
n
​


Where:

𝑝
p is the probability of the team winning.
𝑋
1
,
𝑋
2
,
…
,
𝑋
𝑛
X
1
​
 ,X
2
​
 ,…,X
n
​
  are the predictor variables.
𝛽
0
,
𝛽
1
,
𝛽
2
,
…
,
𝛽
𝑛
β
0
​
 ,β
1
​
 ,β
2
​
 ,…,β
n
​
  are the coefficients to be estimated.
Conclusion
Predicting the winner of a football game using Simple Linear Regression is not appropriate due to the binary nature of the outcome and the complexity of influencing factors. Logistic regression or more advanced machine learning models should be used instead for better accuracy and handling of binary outcomes.
"""